services:
  node:
    image: 'learning/typescript5:local'
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      - js:/usr/src/app/js/
      - node_modules:/usr/src/app/node_modules/
    ports:
      - '3000:3000'

volumes:
  node_modules:
    driver: local

  js:
    driver: local
